services:
  - type: web
    name: image-captioning-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 10000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
    healthCheckPath: /health
    disk:
      - name: uploads
        mountPath: /app/uploads
        sizeGB: 1
      - name: logs
        mountPath: /app/logs
        sizeGB: 1
    
    # Optional: set the port if needed (Render uses 10000 by default for Docker)
    # You can uncomment the following if you want to explicitly set it
    # envVars:
    #   - key: PORT
    #     value: 10000 